import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/src/components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative min-h-screen bg-cover bg-center"
          style={{ backgroundImage: "url('/back.png')" }}>
            <div className="absolute inset-0 backdrop-blur-[1px] "></div>
            <div>
              <div className="relative z-10">
                {children}
              </div>
            </div>
      </body>
    </html>
  );
}
